import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { authenticate, demoMode, errorMessage } from '../services/api';
import { useApp } from '../context/AppContext';
import { images } from '../data';
export default function Auth({register = false}: {register?: boolean}) {
 const app = useApp(); const navigate = useNavigate(); const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
 return <div className="auth-page"><div className="auth-image" style={{backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.6),transparent),url(${images.garden})`}}><h1>A place to belong.<br/>A table to come back to.</h1></div><div className="auth-form"><span className="eyebrow">WELCOME TO GATHER</span><h1>{register ? 'Your seat is waiting.' : 'Good to see you again.'}</h1><p>{register ? 'Create an account for more moments around the table.' : 'Log in to your next good moment.'}</p>{demoMode && <div className="demo-banner">Demo mode uses a local guest profile. No credentials are submitted or stored.</div>}<form onSubmit={async e => {e.preventDefault(); setBusy(true); setError(''); const values = Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>; try {app.login(demoMode ? {userId:1,fullName:values.fullName || 'Alex Morgan',email:values.email,roles:['CUSTOMER']} : await authenticate(register, values)); navigate('/reservations');} catch(err) {setError(errorMessage(err));} finally {setBusy(false);}}}>{register && <label>Full name<input required name="fullName" autoComplete="name" placeholder="Your full name"/></label>}<label>Email address<input required name="email" autoComplete="email" type="email" placeholder="you@example.com"/></label>{!demoMode && <label>Password<input required name="password" type="password" autoComplete={register ? 'new-password' : 'current-password'} minLength={register ? 8 : 1} placeholder={register ? 'At least 8 characters' : 'Your password'}/></label>}{register && <label>Phone number<input name="phone" type="tel" autoComplete="tel" placeholder="+94 77 123 4567"/></label>}{error && <p className="error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy ? 'One moment…' : demoMode ? 'Continue with demo profile' : register ? 'Create account' : 'Log in'}</button></form><p className="center small">{register ? 'Already part of the table? ' : 'New around here? '}<Link className="text-button" to={register ? '/login' : '/register'}>{register ? 'Log in' : 'Create an account'}</Link></p></div></div>;
}
