-- Persist bookable seating spaces and their presentation details.
SET @space_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='restaurant_tables' AND column_name='display_name')=0, 'ALTER TABLE restaurant_tables ADD COLUMN display_name VARCHAR(255)', 'SELECT 1');
PREPARE space_stmt FROM @space_ddl; EXECUTE space_stmt; DEALLOCATE PREPARE space_stmt;
SET @space_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='restaurant_tables' AND column_name='description')=0, 'ALTER TABLE restaurant_tables ADD COLUMN description VARCHAR(255)', 'SELECT 1');
PREPARE space_stmt FROM @space_ddl; EXECUTE space_stmt; DEALLOCATE PREPARE space_stmt;
SET @space_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='restaurant_tables' AND column_name='image_url')=0, 'ALTER TABLE restaurant_tables ADD COLUMN image_url VARCHAR(255)', 'SELECT 1');
PREPARE space_stmt FROM @space_ddl; EXECUTE space_stmt; DEALLOCATE PREPARE space_stmt;
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'G01',2,'GARDEN','AVAILABLE',TRUE,'The Jasmine Courtyard','A quiet garden table surrounded by greenery.','https://images.pexels.com/photos/17035090/pexels-photo-17035090.jpeg?auto=compress&cs=tinysrgb&w=1000',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='G01');
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'G02',4,'GARDEN','AVAILABLE',TRUE,'The Pergola Table','A shaded garden setting for lunch and relaxed evenings.','https://images.pexels.com/photos/24449039/pexels-photo-24449039.jpeg?auto=compress&cs=tinysrgb&w=1000',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='G02');
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'G03',8,'GARDEN','AVAILABLE',TRUE,'The Garden Gathering','A spacious garden table for family meals and celebrations.','https://images.pexels.com/photos/14025865/pexels-photo-14025865.jpeg?auto=compress&cs=tinysrgb&w=1000',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='G03');
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'O02',4,'OUTDOOR','AVAILABLE',TRUE,'The Sunset Terrace','An open-air table for a leisurely dinner.','https://images.pexels.com/photos/24449039/pexels-photo-24449039.jpeg?auto=compress&cs=tinysrgb&w=1000',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='O02');
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'O03',6,'OUTDOOR','AVAILABLE',TRUE,'The Leafy Patio','A welcoming patio setting with natural light and greenery.','https://images.pexels.com/photos/17035090/pexels-photo-17035090.jpeg?auto=compress&cs=tinysrgb&w=1000',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='O03');
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'W02',2,'WINDOW','AVAILABLE',TRUE,'The Window Nook','A light-filled corner for two.','https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=85',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='W02');
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'I02',6,'INDOOR','AVAILABLE',TRUE,'The Social Table','Comfortable indoor dining for friends and family.','https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=85',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='I02');
INSERT INTO restaurant_tables (table_number,capacity,location,current_status,is_active,display_name,description,image_url,created_at,updated_at) SELECT 'P02',10,'PRIVATE','AVAILABLE',TRUE,'The Gathering Room','A private dining table for group dinners.','/images/occasions/birthday-garden.jpg',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM restaurant_tables WHERE table_number='P02');
